---
# Installing mongodb server
- name: Install python
  apt:
    name: python
    state: latest

- name: add MongoDB GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
    state: present
    filename: mongodb-org-4.0.list

- name: Create /data/db folder
  shell: "mkdir -m 777 -p /data/db"

- name: Update repositories cache and install "mongodb" package
  apt: name=mongodb-org state=present update_cache=true

