---
# Installing mongodb server
- name: Install python
  apt:
    name: python
    state: latest

- name: Install mongodb
  command: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4"
  command: "echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list"
  command: "apt-get update"
  command: apt-get install -y mongodb-org"

- name: Start service mongodb
  command: "service mongod start"
  #  service:
  #  name: mongod
  #  state: started
  #  enabled: yes
