---

# Configuring mysql

# Set root password
# UPDATE mysql.user SET Password=PASSWORD('secret') WHERE User='root';
# FLUSH PRIVILEGES;

- name: Set root Password
  mysql_user: 
    name:     "root" 
    password: "{{ login_password }}" 
    priv:     "*.*:ALL,GRANT"
    host:     "{{ item }}" 
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: mysqld.cnf file
  copy: src=mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql service

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Test DB
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - SHOW DATABASES
  changed_when: False

